const dummyData = {
    categories: [
        { name: "Burgers", description: "Flame-grilled gourmet burgers" },
        { name: "Pizzas", description: "Wood-fired artisan pizzas" },
        { name: "Burritos", description: "Authentic Mexican burritos" },
        { name: "Sandwiches", description: "Loaded deli sandwiches" },
        { name: "Wraps", description: "Fresh and healthy wraps" },
        { name: "Bowls", description: "Nourishing power bowls" },
    ],

    customizations: [
        // Toppings
        { name: "Extra Cheese", price: 25, type: "topping" },
        { name: "Jalapeños", price: 20, type: "topping" },
        { name: "Caramelized Onions", price: 15, type: "topping" },
        { name: "Kalamata Olives", price: 18, type: "topping" },
        { name: "Sautéed Mushrooms", price: 20, type: "topping" },
        { name: "Sun-dried Tomatoes", price: 15, type: "topping" },
        { name: "Crispy Bacon", price: 30, type: "topping" },
        { name: "Sliced Avocado", price: 35, type: "topping" },
        { name: "Truffle Aioli", price: 40, type: "topping" },
        { name: "Pickled Relish", price: 12, type: "topping" },

        // Sides
        { name: "Craft Lemonade", price: 30, type: "side" },
        { name: "Seasoned Fries", price: 35, type: "side" },
        { name: "Garlic Breadsticks", price: 40, type: "side" },
        { name: "Chicken Tenders", price: 50, type: "side" },
        { name: "Iced Matcha", price: 32, type: "side" },
        { name: "Caesar Salad", price: 38, type: "side" },
        { name: "Loaded Potato Wedges", price: 42, type: "side" },
        { name: "Mozzarella Sticks", price: 45, type: "side" },
        { name: "Grilled Corn on the Cob", price: 28, type: "side" },
        { name: "Lava Cake", price: 48, type: "side" },
    ],

    menu: [
        {
            name: "TastyGo Classic Burger",
            description: "Flame-grilled beef patty, aged cheddar, butter lettuce, vine tomato, TastyGo sauce",
            image_url:
                "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=60",
            price: 25.99,
            rating: 4.5,
            calories: 550,
            protein: 25,
            category_name: "Burgers",
            customizations: ["Extra Cheese", "Craft Lemonade", "Seasoned Fries", "Caramelized Onions", "Crispy Bacon"],
        },
        {
            name: "Pepperoni Supreme",
            description: "Hand-tossed crust, San Marzano sauce, mozzarella, premium pepperoni",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/023/742/417/large_2x/pepperoni-pizza-isolated-illustration-ai-generative-free-png.png",
            price: 30.99,
            rating: 4.7,
            calories: 700,
            protein: 30,
            category_name: "Pizzas",
            customizations: [
                "Extra Cheese",
                "Jalapeños",
                "Garlic Breadsticks",
                "Craft Lemonade",
                "Kalamata Olives",
            ],
        },
        {
            name: "Spicy Fiesta Burrito",
            description: "Seasoned black beans, cilantro lime rice, pico de gallo, chipotle crema",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/055/133/581/large_2x/deliciously-grilled-burritos-filled-with-beans-corn-and-fresh-vegetables-served-with-lime-wedge-and-cilantro-isolated-on-transparent-background-free-png.png",
            price: 20.99,
            rating: 4.2,
            calories: 480,
            protein: 18,
            category_name: "Burritos",
            customizations: ["Jalapeños", "Iced Matcha", "Seasoned Fries", "Caesar Salad"],
        },
        {
            name: "Smoky BBQ Burger",
            description: "Hickory-smoked BBQ glaze, applewood bacon, aged cheddar on brioche",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/060/236/245/large_2x/a-large-hamburger-with-cheese-onions-and-lettuce-free-png.png",
            price: 27.50,
            rating: 4.8,
            calories: 650,
            protein: 29,
            category_name: "Burgers",
            customizations: ["Caramelized Onions", "Seasoned Fries", "Craft Lemonade", "Crispy Bacon", "Sliced Avocado"],
        },
        {
            name: "Mediterranean Chicken Wrap",
            description: "Grilled chicken, feta, hummus, roasted peppers, tzatziki in a spinach tortilla",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/048/930/603/large_2x/caesar-wrap-grilled-chicken-isolated-on-transparent-background-free-png.png",
            price: 21.50,
            rating: 4.4,
            calories: 490,
            protein: 28,
            category_name: "Wraps",
            customizations: ["Extra Cheese", "Craft Lemonade", "Loaded Potato Wedges", "Sun-dried Tomatoes"],
        },
        {
            name: "Tuscan Veggie Sandwich",
            description: "Roasted eggplant, pesto genovese, sun-dried tomatoes, fresh mozzarella on ciabatta",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/047/832/012/large_2x/grilled-sesame-seed-bread-veggie-sandwich-with-tomato-and-onion-free-png.png",
            price: 19.99,
            rating: 4.1,
            calories: 420,
            protein: 19,
            category_name: "Sandwiches",
            customizations: ["Sautéed Mushrooms", "Kalamata Olives", "Mozzarella Sticks", "Iced Matcha"],
        },
        {
            name: "TastyGo Double Stack",
            description: "Two flame-grilled patties, double cheddar, special TastyGo sauce, sesame bun",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/060/359/627/large_2x/double-cheeseburger-with-lettuce-tomatoes-cheese-and-sesame-bun-free-png.png",
            price: 32.99,
            rating: 4.9,
            calories: 720,
            protein: 35,
            category_name: "Burgers",
            customizations: [
                "Extra Cheese",
                "Caramelized Onions",
                "Seasoned Fries",
                "Craft Lemonade",
                "Chicken Tenders",
            ],
        },
        {
            name: "Tandoori Paneer Wrap",
            description: "Marinated paneer tikka, mint yogurt, pickled onions, fresh cilantro",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/057/913/530/large_2x/delicious-wraps-a-tantalizing-array-of-wraps-filled-with-vibrant-vegetables-succulent-fillings-and-fresh-ingredients-artfully-arranged-for-a-mouthwatering-culinary-experience-free-png.png",
            price: 23.99,
            rating: 4.6,
            calories: 470,
            protein: 20,
            category_name: "Wraps",
            customizations: ["Jalapeños", "Sun-dried Tomatoes", "Caesar Salad", "Seasoned Fries", "Iced Matcha"],
        },
        {
            name: "TastyGo Power Bowl",
            description: "Quinoa, roasted chickpeas, avocado, pickled beets, tahini dressing",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/057/466/374/large_2x/healthy-quinoa-bowl-with-avocado-tomato-and-black-beans-ingredients-free-png.png",
            price: 26.49,
            rating: 4.7,
            calories: 610,
            protein: 24,
            category_name: "Bowls",
            customizations: ["Sliced Avocado", "Grilled Corn on the Cob", "Caesar Salad", "Iced Matcha"],
        },
        {
            name: "Cajun Crispy Chicken Sandwich",
            description: "Cajun-spiced crispy chicken, coleslaw, pickles, spicy mayo on potato bun",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/051/814/008/large_2x/a-grilled-chicken-sandwich-with-lettuce-and-tomatoes-free-png.png",
            price: 24.99,
            rating: 4.3,
            calories: 540,
            protein: 26,
            category_name: "Sandwiches",
            customizations: [
                "Jalapeños",
                "Caramelized Onions",
                "Seasoned Fries",
                "Craft Lemonade",
                "Lava Cake",
            ],
        },
        {
            name: "Margherita Napoletana",
            description: "Neapolitan-style crust, DOP San Marzano, fior di latte, fresh basil",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/058/700/845/large_2x/free-isolated-on-transparent-background-delicious-pizza-topped-with-fresh-tomatoes-basil-and-melted-cheese-perfect-for-food-free-png.png",
            price: 26.99,
            rating: 4.1,
            calories: 590,
            protein: 21,
            category_name: "Pizzas",
            customizations: ["Extra Cheese", "Kalamata Olives", "Craft Lemonade", "Garlic Breadsticks"],
        },
        {
            name: "Grilled Salmon Power Bowl",
            description: "Atlantic salmon, brown rice, edamame, cucumber, ginger-sesame dressing",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/056/106/379/large_2x/top-view-salad-with-chicken-avocado-tomatoes-and-lettuce-free-png.png",
            price: 29.99,
            rating: 4.8,
            calories: 580,
            protein: 38,
            category_name: "Bowls",
            customizations: ["Sliced Avocado", "Caesar Salad", "Grilled Corn on the Cob", "Iced Matcha"],
        },
        {
            name: "Chipotle Bean Burrito",
            description: "Slow-cooked pinto beans, chipotle adobo, Mexican rice, guacamole, queso fresco",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/056/565/254/large_2x/burrito-with-cauliflower-and-vegetables-free-png.png",
            price: 24.99,
            rating: 4.2,
            calories: 510,
            protein: 22,
            category_name: "Burritos",
            customizations: ["Jalapeños", "Seasoned Fries", "Garlic Breadsticks", "Craft Lemonade"],
        },
        {
            name: "Turkey Club Supreme",
            description: "Oven-roasted turkey, applewood bacon, avocado, Swiss cheese on multigrain",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/060/364/135/large_2x/a-flavorful-club-sandwich-with-turkey-bacon-and-fresh-vegetables-sliced-and-isolated-on-a-transparent-background-free-png.png",
            price: 27.49,
            rating: 4.5,
            calories: 610,
            protein: 31,
            category_name: "Sandwiches",
            customizations: ["Crispy Bacon", "Sun-dried Tomatoes", "Mozzarella Sticks", "Iced Matcha"],
        },
    ],
};

export default dummyData;
